/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare/worker/worker-configuration.d.ts` (hash: 93a0270caf781f5feedf08434a4332a7)
interface __BaseEnv_Env {
	RESUME_BUCKET: R2Bucket;
	DB: D1Database;
	OPENAI_MODEL: "gpt-5.4-mini";
	APP_ORIGIN: string;
	CLERK_JWKS_URL: string;
	CLERK_ISSUER: string;
	CLERK_AUTHORIZED_PARTIES: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
