/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=cloudflare/typegen.env --include-runtime=false cloudflare/worker/worker-configuration.d.ts` (hash: 86ec73b735bb1c8e0a9c84ff68bfd0e1)
interface __BaseEnv_Env {
	RESUME_BUCKET: R2Bucket;
	DB: D1Database;
	APP_ORIGIN: string;
	DEFAULT_LLM_PROVIDER: string;
	OPENAI_MODEL: string;
	OPENAI_API_KEY: string;
	CLERK_JWKS_URL: string;
	CLERK_ISSUER: string;
	CLERK_AUTHORIZED_PARTIES: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_PRICE_ID: string;
	BILLING_SUCCESS_URL: string;
	BILLING_CANCEL_URL: string;
	BILLING_PORTAL_RETURN_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
