/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=cloudflare/typegen.env --include-runtime=false cloudflare/worker/worker-configuration.d.ts` (hash: 57fa644e1029f2e0920bca531a720d60)
interface __BaseEnv_Env {
	RESUME_BUCKET: R2Bucket;
	DB: D1Database;
	BROWSER: BrowserRun;
	APP_ORIGIN: string;
	DEFAULT_LLM_PROVIDER: string;
	OPENAI_MODEL: string;
	OPENAI_API_KEY: string;
	CLERK_JWKS_URL: string;
	CLERK_ISSUER: string;
	CLERK_AUTHORIZED_PARTIES: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_PRICE_MONTHLY_ID: string;
	STRIPE_PRICE_6_MONTH_ID: string;
	STRIPE_PRICE_YEARLY_ID: string;
	BILLING_SUCCESS_URL: string;
	BILLING_CANCEL_URL: string;
	BILLING_PORTAL_RETURN_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "DEFAULT_LLM_PROVIDER" | "OPENAI_MODEL" | "OPENAI_API_KEY" | "CLERK_JWKS_URL" | "CLERK_ISSUER" | "CLERK_AUTHORIZED_PARTIES" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_PRICE_MONTHLY_ID" | "STRIPE_PRICE_6_MONTH_ID" | "STRIPE_PRICE_YEARLY_ID" | "BILLING_SUCCESS_URL" | "BILLING_CANCEL_URL" | "BILLING_PORTAL_RETURN_URL">> {}
}
