import { resumeToPlainText, type StructuredResume } from "./resume";
import type { ResumeDocument, ResumeSection } from "./resumeDocument";
import {
  getResumeTemplate,
  orderSectionsForTemplate,
  type ResumeTemplate,
  type ResumeTemplateId,
} from "./resumeTemplates";

const FILE_BASENAME = "syncresume-optimized-resume";

export async function downloadDocx(resume: StructuredResume) {
  const { Document, Packer } = await import("docx");
  const document = new Document({
    creator: "SyncResume",
    title: "Optimized resume",
    description: "ATS-safe resume generated by SyncResume.",
    sections: [
      {
        properties: {},
        children: await buildDocxParagraphs(resume),
      },
    ],
  });
  const blob = await Packer.toBlob(document);
  saveBlob(blob, `${FILE_BASENAME}.docx`);
}

export async function downloadPdf(resume: StructuredResume) {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 54,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  const addPageIfNeeded = (height = 16) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  const addHeading = (text: string) => {
    addPageIfNeeded(22);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.text(text.toUpperCase(), page.margin, y);
    y += 18;
  };

  const addText = (text: string, options: { bold?: boolean; indent?: number } = {}) => {
    pdf.setFont("helvetica", options.bold ? "bold" : "normal");
    pdf.setFontSize(10);
    const indent = options.indent ?? 0;
    const lines = pdf.splitTextToSize(text, maxWidth - indent);
    for (const line of lines) {
      addPageIfNeeded(14);
      pdf.text(line, page.margin + indent, y);
      y += 14;
    }
  };

  if (resume.summary.trim()) {
    addHeading("Summary");
    addText(resume.summary.trim());
    y += 10;
  }

  if (resume.experience.length > 0) {
    addHeading("Experience");
    for (const role of resume.experience) {
      const heading = [role.title, role.company, role.location, role.dates]
        .map((part) => part.trim())
        .filter(Boolean)
        .join(" | ");
      if (heading) {
        addText(heading, { bold: true });
      }
      for (const bullet of role.bullets) {
        addText(`- ${bullet}`, { indent: 12 });
      }
      y += 8;
    }
  }

  if (resume.skills.length > 0) {
    addHeading("Skills");
    addText(resume.skills.join(", "));
    y += 10;
  }

  if (resume.education.length > 0) {
    addHeading("Education");
    for (const item of resume.education) {
      addText(item);
    }
  }

  pdf.save(`${FILE_BASENAME}.pdf`);
}

export async function downloadTextPdf(text: string, fileName = "syncresume-extracted-resume.pdf") {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 54,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  const addPageIfNeeded = (height = 14) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  const normalizedText = text.replace(/\r/g, "").replace(/\n{3,}/g, "\n\n").trim();
  for (const paragraph of normalizedText.split("\n")) {
    const line = paragraph.trim();
    if (!line) {
      y += 8;
      continue;
    }

    const lines = pdf.splitTextToSize(line, maxWidth);
    for (const wrappedLine of lines) {
      addPageIfNeeded();
      pdf.text(wrappedLine, page.margin, y);
      y += 14;
    }
  }

  pdf.save(sanitizeDownloadFileName(fileName));
}

export async function downloadResumeDocumentPdf(
  document: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName = "syncresume-resume.pdf",
) {
  const { jsPDF } = await import("jspdf");
  const template = getResumeTemplate(templateId);
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: template.pdf.margin,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  const addPageIfNeeded = (height = template.pdf.lineHeight) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  const addText = (
    text: string,
    options: { bold?: boolean; center?: boolean; indent?: number; size?: number } = {},
  ) => {
    const indent = options.indent ?? 0;
    pdf.setFont("helvetica", options.bold ? "bold" : "normal");
    pdf.setFontSize(options.size ?? template.pdf.fontSize);
    const lines = pdf.splitTextToSize(text, maxWidth - indent);
    for (const line of lines) {
      addPageIfNeeded(template.pdf.lineHeight);
      pdf.text(line, options.center ? page.width / 2 : page.margin + indent, y, {
        align: options.center ? "center" : "left",
      });
      y += template.pdf.lineHeight;
    }
  };

  const addHeading = (text: string) => {
    y += Math.max(4, template.pdf.sectionGap - 4);
    addPageIfNeeded(template.pdf.lineHeight + 6);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(template.pdf.headingSize);
    pdf.setTextColor(...template.pdf.accent);
    pdf.text(text.toUpperCase(), page.margin, y);
    pdf.setTextColor(17, 17, 18);
    y += template.pdf.lineHeight + 1;
  };

  const sections = orderSectionsForTemplate(document, template);
  const contactSection = sections.find((section) => section.type === "contact");
  if (contactSection) {
    renderPdfContact(contactSection, addText, template);
    y += template.pdf.sectionGap;
  }

  for (const section of sections.filter((item) => item.type !== "contact")) {
    addHeading(section.title);
    renderPdfSectionBody(section, addText, template);
  }

  pdf.save(sanitizeDownloadFileName(fileName));
}

export async function downloadResumeDocumentDocx(
  document: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName = "syncresume-resume.docx",
) {
  const { Document, Packer, Paragraph, TextRun } = await import("docx");
  const template = getResumeTemplate(templateId);
  const sections = orderSectionsForTemplate(document, template);
  const paragraphs: InstanceType<typeof Paragraph>[] = [];
  const addText = (text: string, options: { bold?: boolean; center?: boolean; size?: number } = {}) => {
    paragraphs.push(
      new Paragraph({
        alignment: options.center ? "center" : undefined,
        spacing: { after: template.density === "compact" ? 50 : 80 },
        children: [new TextRun({ text, bold: options.bold, size: options.size ?? 21 })],
      }),
    );
  };
  const addHeading = (text: string) => {
    paragraphs.push(
      new Paragraph({
        spacing: { before: template.density === "compact" ? 120 : 180, after: 80 },
        children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 22 })],
      }),
    );
  };

  const contactSection = sections.find((section) => section.type === "contact");
  if (contactSection) {
    const { name, details } = splitContactContent(contactSection.content);
    if (name) addText(name, { bold: true, center: true, size: 24 });
    if (details.length > 0) addText(details.join(" | "), { center: true, size: 19 });
  }

  for (const section of sections.filter((item) => item.type !== "contact")) {
    addHeading(section.title);
    for (const line of section.content.split("\n").map((item) => item.trim()).filter(Boolean)) {
      addText(line);
    }
  }

  const docx = new Document({
    creator: "SyncResume",
    title: document.title,
    description: `${template.name} resume generated by SyncResume.`,
    sections: [{ properties: {}, children: paragraphs }],
  });
  const blob = await Packer.toBlob(docx);
  saveBlob(blob, sanitizeDownloadFileName(fileName).replace(/\.pdf$/, ".docx"));
}

export async function copyPlainText(resume: StructuredResume) {
  await navigator.clipboard.writeText(resumeToPlainText(resume));
}

async function buildDocxParagraphs(resume: StructuredResume) {
  const { Paragraph, TextRun } = await import("docx");
  const paragraphs: InstanceType<typeof Paragraph>[] = [];
  const addHeading = (text: string) => {
    paragraphs.push(
      new Paragraph({
        spacing: { before: 180, after: 80 },
        children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 22 })],
      }),
    );
  };
  const addText = (text: string, options: { bold?: boolean } = {}) => {
    paragraphs.push(
      new Paragraph({
        spacing: { after: 80 },
        children: [new TextRun({ text, bold: options.bold, size: 21 })],
      }),
    );
  };

  if (resume.summary.trim()) {
    addHeading("Summary");
    addText(resume.summary.trim());
  }

  if (resume.experience.length > 0) {
    addHeading("Experience");
    for (const role of resume.experience) {
      const heading = [role.title, role.company, role.location, role.dates]
        .map((part) => part.trim())
        .filter(Boolean)
        .join(" | ");
      if (heading) {
        addText(heading, { bold: true });
      }
      for (const bullet of role.bullets) {
        addText(`- ${bullet}`);
      }
    }
  }

  if (resume.skills.length > 0) {
    addHeading("Skills");
    addText(resume.skills.join(", "));
  }

  if (resume.education.length > 0) {
    addHeading("Education");
    for (const item of resume.education) {
      addText(item);
    }
  }

  return paragraphs;
}

function saveBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

function sanitizeDownloadFileName(value: string): string {
  const normalized = value.trim().replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9._-]+/g, "-");
  return `${normalized || "syncresume-extracted-resume"}.pdf`;
}

function renderPdfContact(
  section: ResumeSection,
  addText: (text: string, options?: { bold?: boolean; center?: boolean; indent?: number; size?: number }) => void,
  template: ResumeTemplate,
) {
  const { name, details } = splitContactContent(section.content);
  if (name) addText(name, { bold: true, center: true, size: template.pdf.headingSize + 2 });
  if (details.length > 0) addText(details.join(" | "), { center: true, size: template.pdf.fontSize });
}

function splitContactContent(content: string): { name: string; details: string[] } {
  const chunks = content
    .split(/\n|\s*\|\s*/)
    .map((line) => line.trim())
    .filter(Boolean);
  const firstChunk = chunks[0] ?? "";
  const nameMatch = firstChunk.match(/^([A-Z][A-Z.'-]+(?:\s+[A-Z][A-Z.'-]+){1,3})\b/);
  const name = nameMatch?.[1] ?? firstChunk;
  const leftover = firstChunk.slice(name.length).trim();
  return {
    name,
    details: [leftover, ...chunks.slice(1)].filter(Boolean),
  };
}

function renderPdfSectionBody(
  section: ResumeSection,
  addText: (text: string, options?: { bold?: boolean; center?: boolean; indent?: number; size?: number }) => void,
  template: ResumeTemplate,
) {
  const indent = template.density === "compact" ? 8 : 12;
  for (const line of section.content.split("\n").map((item) => item.trim()).filter(Boolean)) {
    if (/^[-•]\s+/.test(line)) {
      addText(`- ${line.replace(/^[-•]\s*/, "")}`, { indent });
    } else {
      addText(line);
    }
  }
}
