import { resumeToPlainText, type StructuredResume } from "./resume";
import type { ResumeDocument } from "./resumeDocument";
import {
  getResumeTemplateDefinition,
  type ResumeTemplateId,
} from "../templates/registry";
import {
  DEFAULT_RESUME_FONT_ID,
  getResumeFontOption,
  type ResumeFontId,
} from "../templates/shared/fonts";
import { cloudflareBlobPostRequest, hasCloudflareConfig } from "./cloudflare/client";
import { getTemplateDocxBlocks } from "../render/renderDocx";
import { formatContactDetailDisplay, parseResumeContact } from "../resume/contact";

export async function downloadTextPdf(text: string, fileName = "syncresume-extracted-resume.pdf") {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 54,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  const addPageIfNeeded = (height = 14) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  const normalizedText = text.replace(/\r/g, "").replace(/\n{3,}/g, "\n\n").trim();
  for (const paragraph of normalizedText.split("\n")) {
    const line = paragraph.trim();
    if (!line) {
      y += 8;
      continue;
    }

    const lines = pdf.splitTextToSize(line, maxWidth);
    for (const wrappedLine of lines) {
      addPageIfNeeded();
      pdf.text(wrappedLine, page.margin, y);
      y += 14;
    }
  }

  pdf.save(sanitizeDownloadFileName(fileName));
}

export async function downloadCoverLetterPdf(text: string, fileName = "syncresume-cover-letter.pdf") {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 54,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  const addPageIfNeeded = (height = 15) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  pdf.setFont("times", "normal");
  pdf.setFontSize(11);

  const normalizedText = text.replace(/\r/g, "").replace(/\n{3,}/g, "\n\n").trim();
  for (const paragraph of normalizedText.split(/\n{2,}/)) {
    const lines = pdf.splitTextToSize(paragraph.replace(/\n/g, " ").trim(), maxWidth);
    for (const line of lines) {
      addPageIfNeeded();
      pdf.text(line, page.margin, y);
      y += 15;
    }
    y += 8;
  }

  pdf.save(withDownloadExtension(fileName, "pdf"));
}

export async function downloadCoverLetterDocx(text: string, fileName = "syncresume-cover-letter.docx") {
  const { Document, Packer, Paragraph, TextRun } = await import("docx");
  const paragraphs = text
    .replace(/\r/g, "")
    .trim()
    .split(/\n{2,}/)
    .map((paragraph) =>
      new Paragraph({
        spacing: { after: 180 },
        children: [new TextRun({ text: paragraph.replace(/\n/g, " ").trim(), size: 22, font: "Times New Roman" })],
      }),
    );

  const document = new Document({
    creator: "SyncResume",
    title: "Cover letter",
    description: "Cover letter generated by SyncResume.",
    sections: [{ properties: {}, children: paragraphs }],
  });

  const blob = await Packer.toBlob(document);
  saveBlob(blob, withDownloadExtension(fileName, "docx"));
}

export async function downloadResumeDocumentPdf(
  resumeDocument: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName = "syncresume-resume.pdf",
  fontId?: ResumeFontId,
) {
  if (!hasCloudflareConfig()) {
    await printResumeDocumentPdf(resumeDocument, templateId, fileName, fontId);
    return;
  }

  const pdfHtml = await renderResumeDocumentPdfHtml(resumeDocument, templateId, fileName, fontId);
  const blob = await cloudflareBlobPostRequest("/api/exports/pdf", {
    fileName: withDownloadExtension(fileName, "pdf"),
    html: pdfHtml,
    resumeDocument,
    templateId,
    fontId: fontId ?? DEFAULT_RESUME_FONT_ID,
  });

  saveBlob(blob, withDownloadExtension(fileName, "pdf"));
}

async function printResumeDocumentPdf(
  resumeDocument: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName: string,
  fontId?: ResumeFontId,
) {
  const html = await renderResumeDocumentPdfHtml(resumeDocument, templateId, fileName, fontId);
  const printWindow = window.open("", "_blank", "noopener,noreferrer");
  if (!printWindow) {
    throw new Error("Allow popups to print this resume.");
  }

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();

  await new Promise<void>((resolve) => {
    const finish = () => resolve();
    printWindow.addEventListener("afterprint", finish, { once: true });
    printWindow.setTimeout(finish, 60000);
    printWindow.setTimeout(() => printWindow.print(), 250);
  });
}

async function renderResumeDocumentPdfHtml(
  resumeDocument: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName: string,
  fontId?: ResumeFontId,
) {
  if (typeof window === "undefined" || typeof document === "undefined") {
    throw new Error("Browser PDF rendering is not available.");
  }

  const [{ createElement }, { createRoot }, { ResumeTemplatePreview }] = await Promise.all([
    import("react"),
    import("react-dom/client"),
    import("../components/ResumeTemplatePreview"),
  ]);

  const host = document.createElement("div");
  host.id = "syncresume-pdf-render-source";
  host.setAttribute("aria-hidden", "true");
  host.style.cssText = [
    "position:fixed",
    "left:-10000px",
    "top:0",
    "width:8.5in",
    "min-height:11in",
    "opacity:0",
    "pointer-events:none",
    "background:#fff",
  ].join(";");

  document.body.appendChild(host);

  const root = createRoot(host);
  try {
    root.render(
      createElement(ResumeTemplatePreview, {
        document: resumeDocument,
        templateId,
        fontId: fontId ?? DEFAULT_RESUME_FONT_ID,
      }),
    );

    await waitForPrintRender();
    await waitForBrowserFonts();

    const styles = collectPdfExportStyles();
    const title = escapeHtml(sanitizeDownloadBaseName(fileName) || "syncresume-resume");

    return [
      "<!doctype html>",
      '<html lang="en">',
      "<head>",
      '<meta charset="utf-8" />',
      '<meta name="viewport" content="width=device-width, initial-scale=1" />',
      `<title>${title}</title>`,
      `<style>${escapeStyleText(styles)}</style>`,
      "</head>",
      '<body><div id="syncresume-pdf-root">',
      host.innerHTML,
      "</div></body>",
      "</html>",
    ].join("");
  } finally {
    root.unmount();
    host.remove();
  }
}

function collectPdfExportStyles() {
  const styles: string[] = [];

  document.querySelectorAll("style").forEach((style) => {
    if (style.id === "syncresume-print-styles") return;
    if (style.textContent) styles.push(style.textContent);
  });

  Array.from(document.styleSheets).forEach((sheet) => {
    try {
      const css = Array.from(sheet.cssRules)
        .map((rule) => rule.cssText)
        .join("\n");
      if (css) styles.push(css);
    } catch {
      // Cross-origin stylesheets cannot be serialized; the app styles are same-origin.
    }
  });

  styles.push(`
@page {
  size: letter;
  margin: 0;
}

html,
body {
  width: 8.5in;
  min-height: 11in;
  margin: 0;
  padding: 0;
  background: #fff;
}

body {
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}

#syncresume-pdf-root,
#syncresume-pdf-root .resume-template-font-scope {
  display: block;
  width: 8.5in;
  min-height: 11in;
  margin: 0;
  padding: 0;
  background: #fff;
}

#syncresume-pdf-root .resume-template-preview {
  width: 8.5in !important;
  min-height: 11in !important;
  margin: 0 !important;
  border: 0 !important;
  border-radius: 0 !important;
  box-shadow: none !important;
  transform: none !important;
  overflow: visible !important;
}

#syncresume-pdf-root :where(button, .section-edit-controls, .section-format-controls, .document-section-delete, .add-section-inline-form, .add-section-trigger) {
  display: none !important;
}
`);

  return styles.join("\n");
}

function waitForPrintRender() {
  return new Promise<void>((resolve) => {
    window.requestAnimationFrame(() => {
      window.requestAnimationFrame(() => resolve());
    });
  });
}

async function waitForBrowserFonts() {
  if (!("fonts" in document)) return;

  try {
    await document.fonts.ready;
  } catch {
    // Font readiness should not block export; the browser will use fallbacks if needed.
  }
}

export async function downloadResumeDocumentDocx(
  document: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName = "syncresume-resume.docx",
  fontId?: ResumeFontId,
) {
  const { Document, ExternalHyperlink, Packer, Paragraph, TextRun } = await import("docx");
  const template = getResumeTemplateDefinition(templateId);
  const font = fontId ? getResumeFontOption(fontId) : null;
  const docxFont = font?.docxFamily;
  const blocks = getTemplateDocxBlocks(document, templateId);
  const paragraphs: InstanceType<typeof Paragraph>[] = [];
  const addText = (text: string, options: { bold?: boolean; center?: boolean; size?: number } = {}) => {
    paragraphs.push(
      new Paragraph({
        alignment: options.center ? "center" : undefined,
        spacing: { after: template.density === "compact" ? 50 : 80 },
        children: [new TextRun({ text, bold: options.bold, size: options.size ?? 21, font: docxFont })],
      }),
    );
  };
  const addHeading = (text: string) => {
    paragraphs.push(
      new Paragraph({
        spacing: { before: template.density === "compact" ? 120 : 180, after: 80 },
        children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 22, font: docxFont })],
      }),
    );
  };
  const addContactDetails = (details: string[]) => {
    const children: Array<InstanceType<typeof TextRun> | InstanceType<typeof ExternalHyperlink>> = [];
    details.forEach((detail, index) => {
      if (index > 0) {
        children.push(new TextRun({ text: " | ", size: 19, font: docxFont }));
      }

      const label = formatContactDetailDisplay(detail);
      const href = getContactDetailHref(detail);
      if (href) {
        children.push(
          new ExternalHyperlink({
            link: href,
            children: [new TextRun({ text: label, size: 19, font: docxFont, style: "Hyperlink" })],
          }),
        );
      } else {
        children.push(new TextRun({ text: label, size: 19, font: docxFont }));
      }
    });

    paragraphs.push(
      new Paragraph({
        alignment: "center",
        spacing: { after: template.density === "compact" ? 50 : 80 },
        children,
      }),
    );
  };

  for (const block of blocks) {
    if (block.isContact) {
      const { name, details } = parseResumeContact(block.lines.join(" | "), document.title);
      if (name) addText(name, { bold: true, center: true, size: 24 });
      if (details.length > 0) {
        addContactDetails(details);
      }
      continue;
    }

    addHeading(block.title);
    for (const line of block.lines) {
      addText(line.replace(/^[-•]\s*/, ""));
    }
  }

  const docx = new Document({
    creator: "SyncResume",
    title: document.title,
    description: `${template.name} resume generated by SyncResume.`,
    sections: [{ properties: {}, children: paragraphs }],
  });
  const blob = await Packer.toBlob(docx);
  saveBlob(blob, sanitizeDownloadFileName(fileName).replace(/\.pdf$/, ".docx"));
}

export async function copyPlainText(resume: StructuredResume) {
  await navigator.clipboard.writeText(resumeToPlainText(resume));
}

function saveBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

function sanitizeDownloadFileName(value: string): string {
  const normalized = sanitizeDownloadBaseName(value);
  return `${normalized || "syncresume-extracted-resume"}.pdf`;
}

function withDownloadExtension(value: string, extension: "docx" | "pdf"): string {
  const fallback = extension === "docx" ? "syncresume-cover-letter" : "syncresume-cover-letter";
  return `${sanitizeDownloadBaseName(value) || fallback}.${extension}`;
}

function getContactDetailHref(value: string): string | null {
  const trimmed = value.trim();
  const email = trimmed.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0];
  if (email) return `mailto:${email}`;

  const explicitUrl = trimmed.match(/https?:\/\/[^\s|]+/i)?.[0];
  if (explicitUrl) return explicitUrl;

  const webPath = trimmed.match(/\b(?:www\.)?(?:github\.com|linkedin\.com|[a-z0-9-]+\.[a-z]{2,})(?:\/[^\s|]*)?/i)?.[0];
  if (!webPath) return null;
  return `https://${webPath.replace(/^www\./i, "www.")}`;
}

function sanitizeDownloadBaseName(value: string): string {
  return value.trim().replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9._-]+/g, "-");
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeStyleText(value: string): string {
  return value.replace(/<\/style/gi, "<\\/style");
}
