import { resumeToPlainText, type StructuredResume } from "./resume";
import type { ResumeDocument } from "./resumeDocument";
import {
  getResumeTemplateDefinition,
  type ResumeTemplateId,
} from "../templates/registry";
import { getTemplateDocxBlocks } from "../render/renderDocx";
import { parseResumeContact } from "../resume/contact";

const FILE_BASENAME = "syncresume-optimized-resume";
const PDF_CONTINUATION_TOP_MARGIN = 34;

export async function downloadDocx(resume: StructuredResume) {
  const { Document, Packer } = await import("docx");
  const document = new Document({
    creator: "SyncResume",
    title: "Optimized resume",
    description: "ATS-safe resume generated by SyncResume.",
    sections: [
      {
        properties: {},
        children: await buildDocxParagraphs(resume),
      },
    ],
  });
  const blob = await Packer.toBlob(document);
  saveBlob(blob, `${FILE_BASENAME}.docx`);
}

export async function downloadPdf(resume: StructuredResume) {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 54,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  const addPageIfNeeded = (height = 16) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  const addHeading = (text: string) => {
    addPageIfNeeded(22);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.text(text.toUpperCase(), page.margin, y);
    y += 18;
  };

  const addText = (text: string, options: { bold?: boolean; indent?: number } = {}) => {
    pdf.setFont("helvetica", options.bold ? "bold" : "normal");
    pdf.setFontSize(10);
    const indent = options.indent ?? 0;
    const lines = pdf.splitTextToSize(text, maxWidth - indent);
    for (const line of lines) {
      addPageIfNeeded(14);
      pdf.text(line, page.margin + indent, y);
      y += 14;
    }
  };

  if (resume.summary.trim()) {
    addHeading("Summary");
    addText(resume.summary.trim());
    y += 10;
  }

  if (resume.experience.length > 0) {
    addHeading("Experience");
    for (const role of resume.experience) {
      const heading = [role.title, role.company, role.location, role.dates]
        .map((part) => part.trim())
        .filter(Boolean)
        .join(" | ");
      if (heading) {
        addText(heading, { bold: true });
      }
      for (const bullet of role.bullets) {
        addText(`- ${bullet}`, { indent: 12 });
      }
      y += 8;
    }
  }

  if (resume.skills.length > 0) {
    addHeading("Skills");
    addText(resume.skills.join(", "));
    y += 10;
  }

  if (resume.education.length > 0) {
    addHeading("Education");
    for (const item of resume.education) {
      addText(item);
    }
  }

  pdf.save(`${FILE_BASENAME}.pdf`);
}

export async function downloadTextPdf(text: string, fileName = "syncresume-extracted-resume.pdf") {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ unit: "pt", format: "letter" });
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 54,
  };
  const maxWidth = page.width - page.margin * 2;
  let y = page.margin;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  const addPageIfNeeded = (height = 14) => {
    if (y + height > page.height - page.margin) {
      pdf.addPage();
      y = page.margin;
    }
  };

  const normalizedText = text.replace(/\r/g, "").replace(/\n{3,}/g, "\n\n").trim();
  for (const paragraph of normalizedText.split("\n")) {
    const line = paragraph.trim();
    if (!line) {
      y += 8;
      continue;
    }

    const lines = pdf.splitTextToSize(line, maxWidth);
    for (const wrappedLine of lines) {
      addPageIfNeeded();
      pdf.text(wrappedLine, page.margin, y);
      y += 14;
    }
  }

  pdf.save(sanitizeDownloadFileName(fileName));
}

export async function downloadResumeDocumentPdf(
  resumeDocument: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName = "syncresume-resume.pdf",
) {
  const { jsPDF } = await import("jspdf");
  const { createRoot } = await import("react-dom/client");
  const html2canvas = (await import("html2canvas")).default;
  const { renderResumeHtmlElement } = await import("../render/renderHtml");

  const host = document.createElement("div");
  const renderTarget = document.createElement("div");
  host.className = "resume-pdf-render-host";
  renderTarget.className = "resume-pdf-render-target";
  host.appendChild(renderTarget);
  document.body.appendChild(host);

  const root = createRoot(renderTarget);

  try {
    root.render(renderResumeHtmlElement(resumeDocument, templateId));
    await waitForBrowserPaint();
    await waitForBrowserPaint();

    const previewElement = renderTarget.querySelector(".resume-template-preview") as HTMLElement | null;
    if (!previewElement) {
      throw new Error("Could not render resume template.");
    }

    const canvas = await html2canvas(previewElement, {
      backgroundColor: "#f7f7f4",
      logging: false,
      scale: 2,
      useCORS: true,
      width: previewElement.scrollWidth,
      height: previewElement.scrollHeight,
      windowWidth: previewElement.scrollWidth,
      windowHeight: previewElement.scrollHeight,
    });

    const pdf = new jsPDF({ unit: "pt", format: "letter", orientation: "portrait" });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const safeCutPositions = getSafePdfCutPositions(previewElement, canvas.width / previewElement.scrollWidth);
    let sourceY = 0;
    let pageIndex = 0;

    while (sourceY < canvas.height) {
      const pageTopMargin = pageIndex === 0 ? 0 : PDF_CONTINUATION_TOP_MARGIN;
      const pageDrawHeight = pageHeight - pageTopMargin;
      const sliceHeight = Math.floor((pageDrawHeight / pageWidth) * canvas.width);
      const height = choosePdfSliceHeight(sourceY, sliceHeight, canvas.height, safeCutPositions);
      const pageCanvas = document.createElement("canvas");
      pageCanvas.width = canvas.width;
      pageCanvas.height = height;
      const ctx = pageCanvas.getContext("2d");
      if (!ctx) throw new Error("Could not prepare resume PDF page.");

      ctx.drawImage(canvas, 0, sourceY, canvas.width, height, 0, 0, canvas.width, height);
      if (pageIndex > 0) pdf.addPage();
      pdf.addImage(
        pageCanvas.toDataURL("image/png"),
        "PNG",
        0,
        pageTopMargin,
        pageWidth,
        (height * pageWidth) / canvas.width,
      );
      sourceY += height;
      pageIndex += 1;
    }

    pdf.save(sanitizeDownloadFileName(fileName));
  } finally {
    root.unmount();
    host.remove();
  }
}

function getSafePdfCutPositions(previewElement: HTMLElement, scale: number): number[] {
  const rootTop = previewElement.getBoundingClientRect().top;
  const selectors = [
    ".template-contact",
    ".template-section",
    ".template-section h2",
    ".template-section-body > p",
    ".template-section-body > ul",
    ".template-section-body li",
    ".template-timeline-entry",
    ".template-project-list li",
  ].join(",");
  const cutPositions = Array.from(previewElement.querySelectorAll<HTMLElement>(selectors))
    .map((element) => Math.ceil((element.getBoundingClientRect().bottom - rootTop + 4) * scale))
    .filter((position) => Number.isFinite(position) && position > 0 && position < previewElement.scrollHeight * scale);

  return [...new Set(cutPositions)].sort((left, right) => left - right);
}

function choosePdfSliceHeight(
  sourceY: number,
  idealSliceHeight: number,
  totalHeight: number,
  safeCutPositions: number[],
): number {
  const remainingHeight = totalHeight - sourceY;
  if (remainingHeight <= idealSliceHeight) return remainingHeight;

  const idealCut = sourceY + idealSliceHeight;
  const minimumCut = sourceY + idealSliceHeight * 0.68;
  const guardedCut = idealCut - 12;
  const safeCut = safeCutPositions
    .filter((position) => position > minimumCut && position < guardedCut)
    .at(-1);

  return Math.max(1, Math.floor((safeCut ?? idealCut) - sourceY));
}

export async function downloadResumeDocumentDocx(
  document: ResumeDocument,
  templateId: ResumeTemplateId,
  fileName = "syncresume-resume.docx",
) {
  const { Document, Packer, Paragraph, TextRun } = await import("docx");
  const template = getResumeTemplateDefinition(templateId);
  const blocks = getTemplateDocxBlocks(document, templateId);
  const paragraphs: InstanceType<typeof Paragraph>[] = [];
  const addText = (text: string, options: { bold?: boolean; center?: boolean; size?: number } = {}) => {
    paragraphs.push(
      new Paragraph({
        alignment: options.center ? "center" : undefined,
        spacing: { after: template.density === "compact" ? 50 : 80 },
        children: [new TextRun({ text, bold: options.bold, size: options.size ?? 21 })],
      }),
    );
  };
  const addHeading = (text: string) => {
    paragraphs.push(
      new Paragraph({
        spacing: { before: template.density === "compact" ? 120 : 180, after: 80 },
        children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 22 })],
      }),
    );
  };

  for (const block of blocks) {
    if (block.isContact) {
      const { name, details } = parseResumeContact(block.lines.join(" | "), document.title);
      if (name) addText(name, { bold: true, center: true, size: 24 });
      if (details.length > 0) addText(details.join(" | "), { center: true, size: 19 });
      continue;
    }

    addHeading(block.title);
    for (const line of block.lines) {
      addText(line.replace(/^[-•]\s*/, ""));
    }
  }

  const docx = new Document({
    creator: "SyncResume",
    title: document.title,
    description: `${template.name} resume generated by SyncResume.`,
    sections: [{ properties: {}, children: paragraphs }],
  });
  const blob = await Packer.toBlob(docx);
  saveBlob(blob, sanitizeDownloadFileName(fileName).replace(/\.pdf$/, ".docx"));
}

export async function copyPlainText(resume: StructuredResume) {
  await navigator.clipboard.writeText(resumeToPlainText(resume));
}

async function buildDocxParagraphs(resume: StructuredResume) {
  const { Paragraph, TextRun } = await import("docx");
  const paragraphs: InstanceType<typeof Paragraph>[] = [];
  const addHeading = (text: string) => {
    paragraphs.push(
      new Paragraph({
        spacing: { before: 180, after: 80 },
        children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 22 })],
      }),
    );
  };
  const addText = (text: string, options: { bold?: boolean } = {}) => {
    paragraphs.push(
      new Paragraph({
        spacing: { after: 80 },
        children: [new TextRun({ text, bold: options.bold, size: 21 })],
      }),
    );
  };

  if (resume.summary.trim()) {
    addHeading("Summary");
    addText(resume.summary.trim());
  }

  if (resume.experience.length > 0) {
    addHeading("Experience");
    for (const role of resume.experience) {
      const heading = [role.title, role.company, role.location, role.dates]
        .map((part) => part.trim())
        .filter(Boolean)
        .join(" | ");
      if (heading) {
        addText(heading, { bold: true });
      }
      for (const bullet of role.bullets) {
        addText(`- ${bullet}`);
      }
    }
  }

  if (resume.skills.length > 0) {
    addHeading("Skills");
    addText(resume.skills.join(", "));
  }

  if (resume.education.length > 0) {
    addHeading("Education");
    for (const item of resume.education) {
      addText(item);
    }
  }

  return paragraphs;
}

function saveBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

function waitForBrowserPaint(): Promise<void> {
  return new Promise((resolve) => {
    requestAnimationFrame(() => resolve());
  });
}

function sanitizeDownloadFileName(value: string): string {
  const normalized = value.trim().replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9._-]+/g, "-");
  return `${normalized || "syncresume-extracted-resume"}.pdf`;
}
